
version: 2

models:
  - name: fact_rating
    description: "All the Rating with the details of movies and users who did the rate"
    columns:
      - name: ratingid
        data_type: string
        description: "Rating ID"

      - name: movie_name
        data_type: string
        description: "Movie Name"

      - name: genres
        data_type: string
        description: "Movie Genres"

      - name: moviedate
        data_type: string
        description: "Movie Release Date"

      - name: rating
        data_type: int64
        description: "the Movie Rate"

      - name: userid
        data_type: int64
        description: "ID of user who did the rate"

      - name: gender
        data_type: string
        description: "gender of user"

      - name: user_age
        data_type: string
        description: "age of user"

      - name: user_occupation
        data_type: string
        description: "occupation of user"

      - name: user_zipcode
        data_type: string
        description: "the Zip code of user "

      - name: rating_timestamp
        data_type: timestamp
        description: "the Rating time & date"
